weniv/pythonbest20

codeexec.html, index.html, src/css/style.css
메인 페이지 로고 스타일 복구하고
실행 페이지에도 로고 추가했습니다.
=> 메인 페이지 로고 스타일링 변경 및 실행 페이지 로고 추가

index.html
- index.html 파일 내 meta tag 추가했습니다.
- 도메인 확정 후 url 변경될 예정입니다.
- og태그 이미지 요청 후 변경될 예정입니다.
=> :sparkles: Feat: SEO 작업 

src/css/codeexec.css
- codeexec.css 파일 variable 커스텀 속성 적용했습니다.
=> :lipstick: Edit: variable 커스텀 속성 적용

src/css/codeexec.css, src/css/style.css, src/css/variable.css
- 안쓰이는 변수 삭제
- 변수 적용
- `colorText` 변수가 텍스트뿐만 아니라 배경, border 등에 다양하게 사용되어 기존 네이밍과 통일해서 `colorWhite`로 변경
=> Refactor: 스타일 변수 정리

src/css/style.css
- 문제 풀이 페이지에서 print 구문을 사용하면 페이지 최하단에 터미널이 추가되어 결과가 출력됩니다.
- Result 창에서 오류임을 명시하기 때문에 터미널 속성이 보이지 않게 설정합니다.
-
=> Fix: 문제 풀이 화면에서 터미널 출력 방지

src/css/style.css, src/js/nav.js
- 반응형 모바일 버전 코드에디터 마진 생기는 현상 해결
- 1024px ~ 1200px 사이 navbar 방식 차이가 있어 레이아웃 깨지는 현상 해결
=> :lipstick: edit: 코드에디터 레이아웃 깨짐현상 수정

src/css/style.css
- header fixed로 상단 부분 고정
- PC버전 navBar 위치 고정
- 모바일 버전 navBar 커스텀 스크롤 적용
=> 💄 Edit: header, nav 고정

src/css/style.css
- 모바일 버전 컨텐츠 하부에서 메튜버튼 클릭시 navBar 화면에 보이지 않아 position: fixed;로 변경.
- 변경 전
- 변경 후
=> :lipstick: Edit: 모바일 버전 nav fixed

src/css/style.css, src/js/ad.js
슬라이드 자동 재생과 버튼 조작이 중첩되어 이상하게 슬라이드가 순서대로 넘어가지않던 부분을 수정하였습니다.
- 버튼 조작 시 간헐적인 끊김이 발생합니다.
=> Edit: 광고 슬라이드 자동재생 및 버튼 조작 수정

index.html, src/css/style.css, src/js/ad.js
위니브 장학금 광고 추가, 광고 순서 변경, 좌우 버튼 크기 변경
=> Edit: 광고 슬라이드 수정

index.html, src/js/ad.js
1. 페이지네이션 수정: 라디오버튼 클릭 후 다음 광고로 이동하도록 수정
2. 돔요소 변수명 앞에 $을 추가하여 변수와 돔요소를 구분할 수 있도록 수정 ex) carousel -> $carousel
3. 광고 개수($adList.length), 이미지 변경 시간(sliderTime)을 변수로 선언하여 유지보수가 용이하도록 수정
=> Feat/radio event: 페이지네이션 처리 및 코드 개선

index.html
- format on save로 파이썬 구문이 JS에 맞춰 자동 인덴트 처리되면서 작동 안하는 이슈 수정했습니다
=> Style: 파이썬 인덴트 오류 수정

.vscode/settings.json, src/css/style.css
=> Fix: 스크롤시 .editor이 고정되도록 수정

index.html
- 변경 이유
화면 첫 로딩 시 광고 페이지네이션 첫번째 버튼 3초 뒤 활성화
- 변경 내역
첫번째 radio버튼 checked 속성 추가
=> :bug: Edit: radio 버튼 3초 뒤 활성화되는 현상 해결

src/css/style.css, src/js/parser.js
- li 내부에 숫자(1.)을 제외하고 들어가도록 파싱 수정
- ol에 list-style 적용
=> Feat: 순서가 있는 리스트 스타일에 decimal 적용

src/js/ad.js
- 변경 이유
[페이지네이션] 로딩 시 첫 번째 라디오에서 두 번째 라디오로 넘어가는 데 6초 소요
------
- 변경 내역
광고 캐러셀 즉시 실행하도록 코드 수정
=> :bug: Edit: 광고 실행시간 일정하도록 수정

index.html, src/js/parser.js
- md파일 이미지 alt값 미 생성으로 코드 추가
(이미지 아래 캡션 생성되므로 alt값 ""으로 통일)
- 광고 이미지 alt값 추가
- DOCTYPE 추가
- textarea label 태그 추가
=> :mag: Edit: SEO, 웹접근성 개선

src/css/style.css
- 사용중이지 않은 스타일 속성 정리
- header 최소너비 320px 고정
- 1024px이하의 화면에서 .editor 부분의 레이아웃이 깨지는 현상 수정
=> :lipstick: Edit: 사용하지 않는 스타일 속성 정리

src/css/style.css
- 페이지네이션 도트를 보이지 않도록 처리함
- prev/next 버튼의 조작영역을 확대함
=> Edit: 768px이하 화면에서 광고 슬라이드 수정

src/css/style.css
navBar가 100vh보다 길 때 scroll 생기도록 수정
=> :bug: Edit: navBar y-scroll 추가

src/css/style.css
=> Design: 헤더 로고 레이아웃 수정

src/css/style.css
=> :lipstick: Edit: info 양 옆 box-shadow 제거

src/js/timer.js
- 페이지 이동(새로고침) 시에만 초기화
- 문제 이동 시 타이머 유지
=> Feat: 문제 이동 시에도 타이머가 유지되도록 수정

src/js/event.js
- 다른 문제 이동 시 에러 메시지가 뜨는 현상 수정
- 문제 제출 시에도 결과값이 보이지 않음. (작성한 코드는 로컬 스토리지를 통해 보임)
- 제출 완료한 문제의 경우 결과창 보여주어야할 것 같습니다.
=> Feat: 문제 이동 시 에러 메시지 초기화

src/css/codeexec.css, src/css/style.css
- Run python 페이지에서 스크롤시 경고창이 함께 올라가는 현상
- 헤더가 고정되어 있어 경고창도 함께 고정되도록 설정
=> Design: PyScript 경고창이 헤더 위에 고정되도록 설정

index.html, src/css/style.css, src/js/event.js
=> :lipstick: Add: 결과창 안내메세지 추가

src/css/codeexec.css, src/css/style.css
자스알고랑 동일하게 실행페이지의 '메인으로' 버튼의 배경색이 적용 안되는 에러가 있어 수정했습니다.
=> Fix: 실행 버튼 배경색 적용

src/js/chat.js
- 채팅 컨테이너 여다는 함수 `handleCloseChat`, `handleOpenChat`으로 리팩토링
- 채팅 창 외부 클릭 시 닫히는 기능 추가
=> Feat: 채팅창 외부 클릭시 닫히는 기능 추가

src/css/codeexec.css
vw 2000px 이상에서 footer 너비 초과로 인해 스크롤 생기는 문제 수정했습니다.
=> Fix: 실행페이지 가로 스크롤 제거

src/css/style.css
- 기본 높이 (전)500px -> (현)450px
- 모바일 버전 추가: 400px
=> :lipstick: Edit: 채팅창 기본 높이, 모바일 버전 높이 변경

index.html, src/css/py.css
현재 이스트소프트 과정이 모집하지 않으므로 해당 광고와 관련한 내용이 있는 다음 파일에서 주석처리 해놓았습니다.
- index.html
- py.css
추후 모집 시 링크 수정 및 주석 해제만 해주시면 됩니다.
=> Docs: 오르미 광고 주석처리
